services:
  backend:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - custom_network

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/data
    environment:
      MINIO_ROOT_USER: MINIO
      MINIO_ROOT_PASSWORD: MINIO123
    command: server --console-address ":9001" /data
    networks:
      - custom_network

volumes:
  storage: {}

networks:
  custom_network:
    driver: bridge
          


    

    