services:
  backend:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./gcp-creds.json:/secrets/gcp-creds.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp-creds.json
    ports:
      - "8080:8080"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
