services:
  backend:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - custom_network
    depends_on:
      ollama:
        condition: service_healthy
      database:
        condition: service_started
      

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/data
    environment:
      MINIO_ROOT_USER: MINIO
      MINIO_ROOT_PASSWORD: MINIO123
    command: server --console-address ":9001" /data
    networks:
      - custom_network

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - custom_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    restart: always
    networks:
      - custom_network
    healthcheck:
      test: ["CMD", "bash", "-c", "while ! ollama list | grep 'llama3:8b'; do echo 'Waiting for model...'; sleep 30; done"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 60s

  database:
    image: postgres:alpine
    container_name: db
    restart: always
    env_file:
      - .env.dev
    expose:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - custom_network


volumes:
  storage: {}
  qdrant_data: {}
  ollama_data: {}
  pg_data: {}

networks:
  custom_network:
    driver: bridge

configs:
  qdrant_config:
    content: |
      log_level: INFO      
          


    

    