services:
  backend:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    expose:
      - 8000
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
          


    

    